name: Deploy to EC2

on:
  push:
    branches:
      - main  # Puedes cambiar esta rama según el flujo que desees

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.11.0'  # Cambia a la versión que uses

    - name: Install dependencies
      run: npm install

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        # Instalar dependencias en EC2 y desplegar
        echo "$PRIVATE_KEY" > node.pem
        chmod 600 node.pem

        # Copiar archivos del repositorio a EC2
        scp -i node.pem -o StrictHostKeyChecking=no -r $(pwd)/* $USER@$HOST:/home/$USER/projects/aws-node

        # Conectarse al servidor EC2 y ejecutar comandos para desplegar
        ssh -i node.pem -o StrictHostKeyChecking=no $USER@$HOST << EOF
          # Instalar PM2 si no está instalado
          if ! command -v pm2 &> /dev/null
          then
            echo "PM2 no encontrado, instalando..."
            sudo npm install -g pm2
          fi

          # Crear el directorio del proyecto si no existe
          mkdir -p /home/$USER/projects/aws-node
          cd /home/$USER/projects/aws-node

          # Instalar las dependencias del proyecto
          npm install

          # Iniciar o reiniciar la aplicación con PM2
          pm2 restart all || pm2 start server.js  # Ajusta a tu archivo principal (por ejemplo, 'server.js')
      EOF
 
